language: python
sudo: false
addons:
  apt:
    packages:
    - pandoc
    - python3
script:
 - ./slides/slidy-scripts/check.py # check lectures
 - ./slides/slidy-scripts/gen_slides.sh # render HTML slides using Pandoc
notifications:
  email: false
